export function buildWhatsAppHostBridgeSource(): string {
  return `let bt=null;const YUNYI_WHATSAPP_HOST={
isWhatsapp(){return typeof window!="undefined"&&typeof window.location?.hostname=="string"&&window.location.hostname.includes("whatsapp")},
normalizeTarget(i){if(typeof i=="string"||typeof i=="number")return String(i).trim();if(!i||typeof i!="object")return"";const e=[i.contact,i.phoneNumber,i.contactId,i.contactID,i.id,i._serialized,i.user,i.wid,i.jid,i.remote,i.chatId,i.participant,i.value];for(const t of e){const o=YUNYI_WHATSAPP_HOST.normalizeTarget(t);if(o)return o}return""},
detectType(i,e){const t=typeof i=="object"&&i?i.type||i.contactType||i.chatType||i.messageType:"";if(i?.isGroup===!0||e.includes("@g.us")||/^120363\\d{6,}$/.test(e)||/-\\d+$/.test(e))return"group";if(e.includes("@c.us")||e.includes("@lid"))return"chat";if(t)return t;return"chat"},
toChatId(i){const e=YUNYI_WHATSAPP_HOST.normalizeTarget(i);if(!e)return"";if(e.includes("@"))return e;const t=YUNYI_WHATSAPP_HOST.detectType(i,e);return t==="group"?e+"@g.us":e.replace(/^\\+/,"")+"@c.us"},
describe(i){if(i===null)return"null";if(i===void 0)return"undefined";if(typeof i=="string"||typeof i=="number"||typeof i=="boolean")return String(i);const e=YUNYI_WHATSAPP_HOST.normalizeTarget(i);if(e)return e;try{return JSON.stringify(i)}catch{return String(i)}},
normalizePayload(i){const e=YUNYI_WHATSAPP_HOST.normalizeTarget(i);if(!e)return i;const t=YUNYI_WHATSAPP_HOST.detectType(i,e),o=YUNYI_WHATSAPP_HOST.toChatId(i);if(i&&typeof i=="object")return{...i,rawContactId:e,contactId:o,type:i.type||t};return{rawContactId:e,contactId:o,type:t}},
wrapCustomEvent(i){if(!YUNYI_WHATSAPP_HOST.isWhatsapp()||!i||typeof i!="object"||i.__yunyiWhatsappHostWrapped||!i.sendMessage||typeof i.sendMessage!="object")return i;const e={...i.sendMessage},t=o=>typeof o=="function"?async function(...a){const[s,...c]=a,f=YUNYI_WHATSAPP_HOST.normalizePayload(s);console.log("[yunyi-whatsapp-host]","normalize send target","input="+YUNYI_WHATSAPP_HOST.describe(s),"contactId="+YUNYI_WHATSAPP_HOST.describe(f?.contactId),"type="+YUNYI_WHATSAPP_HOST.describe(f?.type));return await o.call(this,f,...c)}:o;for(const o of["text","image","audio","card"])typeof e[o]=="function"&&(e[o]=t(e[o]));return{...i,sendMessage:e,__yunyiWhatsappHostWrapped:!0}}
};const Kb=i=>{bt=YUNYI_WHATSAPP_HOST.wrapCustomEvent(i),yr.initCustomEvent(bt)},Wb=i=>{yr.addFans(i)};`;
}
