export function buildWhatsAppHostBridgeSource(): string {
  return `const YUNYI_BETTER_SQLITE3_RESOLVER=(()=>{try{const i=require("node:module"),e=require("node:path"),t=require("node:fs"),o=i._load;if(typeof o!="function"||o.__yunyiBetterSqlitePatched)return null;const a=[],s=new Set,c=n=>{if(typeof n!="string"||!n||s.has(n))return;s.add(n),a.push(n)};c(e.join(process.cwd(),"node_modules","better-sqlite3"));if(typeof process.resourcesPath=="string"&&process.resourcesPath){c(e.join(process.resourcesPath,"node_modules","better-sqlite3"));c(e.join(process.resourcesPath,"app","node_modules","better-sqlite3"));c(e.join(process.resourcesPath,"app.asar.unpacked","node_modules","better-sqlite3"));c(e.join(process.resourcesPath,"app.asar.unpacked","app","node_modules","better-sqlite3"))}const f=function(n,r,u){if(n==="better-sqlite3"){for(const l of a)try{if(t.existsSync(l))return o.call(this,l,r,u)}catch{}console.warn("[yunyi-whatsapp-host]","better-sqlite3 fallback candidates exhausted",a)}return o.call(this,n,r,u)};return f.__yunyiBetterSqlitePatched=!0,i._load=f,f}catch(i){return console.warn("[yunyi-whatsapp-host]","better-sqlite3 resolver install failed",i),null}})();let bt=null;const YUNYI_WHATSAPP_HOST={
isWhatsapp(){return typeof window!="undefined"&&typeof window.location?.hostname=="string"&&window.location.hostname.includes("whatsapp")},
isWhatsappRecipePayload(i){return String(i?.recipe?.id||"").toLowerCase().includes("whatsapp")},
normalizeTarget(i){if(typeof i=="string"||typeof i=="number")return String(i).trim();if(!i||typeof i!="object")return"";const e=[i.contact,i.phoneNumber,i.contactId,i.contactID,i.id,i._serialized,i.user,i.wid,i.jid,i.remote,i.chatId,i.participant,i.value];for(const t of e){const o=YUNYI_WHATSAPP_HOST.normalizeTarget(t);if(o)return o}return""},
detectType(i,e){const t=typeof i=="object"&&i?i.type||i.contactType||i.chatType||i.messageType:"";if(i?.isGroup===!0||e.includes("@g.us")||/^120363\\d{6,}$/.test(e)||/-\\d+$/.test(e))return"group";if(e.includes("@c.us")||e.includes("@lid"))return"chat";if(t)return t;return"chat"},
toChatId(i){const e=YUNYI_WHATSAPP_HOST.normalizeTarget(i);if(!e)return"";if(e.includes("@"))return e;const t=YUNYI_WHATSAPP_HOST.detectType(i,e);return t==="group"?e+"@g.us":e.replace(/^\\+/,"")+"@c.us"},
describe(i){if(i===null)return"null";if(i===void 0)return"undefined";if(typeof i=="string"||typeof i=="number"||typeof i=="boolean")return String(i);const e=YUNYI_WHATSAPP_HOST.normalizeTarget(i);if(e)return e;try{return JSON.stringify(i)}catch{return String(i)}},
toClassName(i){return typeof i=="string"?i:Array.isArray(i)?i.join(" "):String(i?.baseVal||i||"")},
extractMessageRow(i){return i?.closest?.(".message-in,.message-out,[data-id],[data-pre-plain-text]")||null},
extractMessageLabel(i){const e=YUNYI_WHATSAPP_HOST.extractMessageRow(i);return e?.getAttribute?.("data-pre-plain-text")||e?.querySelector?.("[data-pre-plain-text]")?.getAttribute?.("data-pre-plain-text")||""},
parseHistoryTimestamp(i){if(!i)return 0;const e=/(\\d{4})[\\/-](\\d{1,2})[\\/-](\\d{1,2})/.exec(i),t=/(\\d{1,2})[\\/-](\\d{1,2})[\\/-](\\d{4})/.exec(i);let o=0,a=0,s=0;if(e?(o=Number(e[1]),a=Number(e[2])-1,s=Number(e[3])):t&&(o=Number(t[3]),a=Number(t[1])-1,s=Number(t[2])),!o)return /昨天|yesterday/i.test(i)?Date.now()-864e5:0;const c=new Date(o,a,s);return Number.isNaN(c.getTime())?0:c.getTime()},
isMetaMessageElement(i){if(!i||i.nodeType!==Node.ELEMENT_NODE)return!1;const e=i,t=String(e.getAttribute("data-testid")||""),o=YUNYI_WHATSAPP_HOST.toClassName(e.className),a=String(e.getAttribute("aria-hidden")||"");if(a==="true"&&(t||o))return!0;if(["msg-meta","msg-status","msg-time","tail","status-dblcheck","msg-dblcheck","msg-check"].includes(t))return!0;return/\\b(message-meta|copyable-text-selectable|x1rg5ohu|x16dsc37)\\b/.test(o)},
stripTrailingMessageMeta(i){if(!i)return"";return i.replace(/\\u200b/g,"").replace(/\\n{3,}/g,"\\n\\n").replace(/[\\s\\u00a0]+/g," ").replace(/(?:\\s|[\\u200b\\u2060])*(?:\\d{1,2}:\\d{2})(?:\\s*[✓✔↻⟳]+)?$/u,"").trim()},
extractMessageText(i){if(!i)return"";const e=YUNYI_WHATSAPP_HOST.extractMessageRow(i)||i,t=Array.from(e.querySelectorAll?.("[data-testid='msg-text'] span.selectable-text.copyable-text,[data-testid='msg-text'] p.copyable-text,[data-testid='msg-text'] [data-lexical-text='true'],span.selectable-text.copyable-text,p.copyable-text")||[]).filter(n=>!YUNYI_WHATSAPP_HOST.isMetaMessageElement(n));if(t.length){const n=t.map(r=>String(r.textContent||"").trim()).filter(Boolean).join("\\n");if(n)return YUNYI_WHATSAPP_HOST.stripTrailingMessageMeta(n)}const o=(n,r)=>{if(!n)return;if(n.nodeType===Node.TEXT_NODE){const l=String(n.textContent||"");l&&r.push(l);return}if(n.nodeType!==Node.ELEMENT_NODE)return;const u=n;if(YUNYI_WHATSAPP_HOST.isMetaMessageElement(u))return;if(u.tagName==="BR"){r.push("\\n");return}if(u.tagName==="IMG"){const l=String(u.getAttribute("alt")||"");l&&r.push(l);return}for(const l of Array.from(u.childNodes||[]))o(l,r)},a=i.matches?.("[data-testid='msg-text'],._akbu,span.selectable-text.copyable-text,p.copyable-text")?i:i.querySelector?.("[data-testid='msg-text'],._akbu,span.selectable-text.copyable-text,p.copyable-text")||e,s=[];o(a,s);return YUNYI_WHATSAPP_HOST.stripTrailingMessageMeta(s.join(""))},
patchRecipeRuntimeConfig(i,e){if(!YUNYI_WHATSAPP_HOST.isWhatsapp()||!YUNYI_WHATSAPP_HOST.isWhatsappRecipePayload(e)||!i||typeof i!="object"||i.__yunyiWhatsappRuntimePatched)return i;const t={...(i.config||{})},o={...(i.method||{})},a=o.getChatInfo,s=o.getMsgTxt,c=o.isHistoryMsg,f=o.getIsMe,b=o.othersNeedTrans;t.main="#main",t.friendList="#pane-side",t.otherfriendLists="#pane-side [role='gridcell'],#pane-side ._ak8o[role='gridcell'],#pane-side [data-testid='cell-frame-container']",t.friendListDown="#pane-side",t.allMsg="._akbu,[data-testid='msg-text'],span.selectable-text.copyable-text,p.copyable-text",t.isObserverSubTree=!0,t.chatDelay=Math.max(Number(t.chatDelay)||0,150),t.initChatDelay=Math.max(Number(t.initChatDelay)||0,150),o.getChatInfo=function(...n){let r=null;try{r=typeof a=="function"?a.apply(this,n):null}catch(l){console.warn("[yunyi-whatsapp-host]","getChatInfo fallback",l)}const u=document.querySelector("#chatActiveIpt")?.value||"",g=document.querySelector("#pane-side [aria-selected='true'][data-id],#pane-side [data-id][aria-selected='true'],#pane-side [aria-selected='true'] [data-id]")?.getAttribute?.("data-id")||"",m=YUNYI_WHATSAPP_HOST.normalizeTarget(u)||YUNYI_WHATSAPP_HOST.normalizeTarget(g)||YUNYI_WHATSAPP_HOST.normalizeTarget(r?.id),k=document.querySelector("header span[dir='auto']"),S=(k?.textContent||r?.name||"").trim(),P=r?.group===!0||document.querySelector("#chatActiveIpt")?.getAttribute("data-isgroup")==="1"||String(m).includes("@g.us");return{id:m||String(r?.id||""),name:S,group:P}},o.getMsgTxt=function(n,...r){const u=YUNYI_WHATSAPP_HOST.extractMessageText(n);if(u)return u;return typeof s=="function"?s.call(this,n,...r):String(n?.textContent||"").trim()},o.isHistoryMsg=function(n,...r){const u=YUNYI_WHATSAPP_HOST.parseHistoryTimestamp(YUNYI_WHATSAPP_HOST.extractMessageLabel(n));if(u){const g=new Date;g.setHours(0,0,0,0);return u<g.getTime()}return typeof c=="function"?c.call(this,n,...r):!1},o.getIsMe=function(n,...r){const u=YUNYI_WHATSAPP_HOST.extractMessageRow(n),g=YUNYI_WHATSAPP_HOST.toClassName(u?.className);if(g.includes("message-out"))return!0;if(g.includes("message-in"))return!1;return typeof f=="function"?f.call(this,n,...r):!1},o.othersNeedTrans=function(n,...r){if(typeof b=="function")try{if(b.call(this,n,...r))return!0}catch(u){console.warn("[yunyi-whatsapp-host]","othersNeedTrans fallback",u)}return!!n?.target?.closest?.("#pane-side [role='gridcell'],#pane-side ._ak8o[role='gridcell'],#pane-side [data-testid='cell-frame-container'],#main header")};const n={...i,config:t,method:o,__yunyiWhatsappRuntimePatched:!0};return console.log("[yunyi-whatsapp-host]","patched whatsapp recipe runtime config"),n},
normalizePayload(i){const e=YUNYI_WHATSAPP_HOST.normalizeTarget(i);if(!e)return i;const t=YUNYI_WHATSAPP_HOST.detectType(i,e),o=YUNYI_WHATSAPP_HOST.toChatId(i);if(i&&typeof i=="object")return{...i,rawContactId:e,contactId:o,type:i.type||t};return{rawContactId:e,contactId:o,type:t}},
wrapCustomEvent(i){if(!YUNYI_WHATSAPP_HOST.isWhatsapp()||!i||typeof i!="object"||i.__yunyiWhatsappHostWrapped||!i.sendMessage||typeof i.sendMessage!="object")return i;const e={...i.sendMessage},t=o=>typeof o=="function"?async function(...a){const[s,...c]=a,f=YUNYI_WHATSAPP_HOST.normalizePayload(s);console.log("[yunyi-whatsapp-host]","normalize send target","input="+YUNYI_WHATSAPP_HOST.describe(s),"contactId="+YUNYI_WHATSAPP_HOST.describe(f?.contactId),"type="+YUNYI_WHATSAPP_HOST.describe(f?.type));return await o.call(this,f,...c)}:o;for(const o of["text","image","audio","card"])typeof e[o]=="function"&&(e[o]=t(e[o]));return{...i,sendMessage:e,__yunyiWhatsappHostWrapped:!0}}
};const Kb=i=>{bt=YUNYI_WHATSAPP_HOST.wrapCustomEvent(i),yr.initCustomEvent(bt)},Wb=i=>{yr.addFans(i)};`;
}
