export function buildWhatsAppGuestDomHelperObjectSource(): string {
  return `toClassName(i){return typeof i=="string"?i:Array.isArray(i)?i.join(" "):String(i?.baseVal||i||"")},
extractMessageRow(i){return i?.closest?.(".message-in,.message-out,[data-id],[data-pre-plain-text]")||null},
extractMessageLabel(i){const e=YUNYI_WHATSAPP_HOST.extractMessageRow(i);return e?.getAttribute?.("data-pre-plain-text")||e?.querySelector?.("[data-pre-plain-text]")?.getAttribute?.("data-pre-plain-text")||""},
parseHistoryTimestamp(i){if(!i)return 0;const e=/(\\d{4})[\\/-](\\d{1,2})[\\/-](\\d{1,2})/.exec(i),t=/(\\d{1,2})[\\/-](\\d{1,2})[\\/-](\\d{4})/.exec(i);let o=0,a=0,s=0;if(e?(o=Number(e[1]),a=Number(e[2])-1,s=Number(e[3])):t&&(o=Number(t[3]),a=Number(t[1])-1,s=Number(t[2])),!o)return /昨天|yesterday/i.test(i)?Date.now()-864e5:0;const c=new Date(o,a,s);return Number.isNaN(c.getTime())?0:c.getTime()},
isMetaMessageElement(i){if(!i||i.nodeType!==Node.ELEMENT_NODE)return!1;const e=i,t=String(e.getAttribute("data-testid")||""),o=YUNYI_WHATSAPP_HOST.toClassName(e.className),a=String(e.getAttribute("aria-hidden")||"");if(a==="true"&&(t||o))return!0;if(["msg-meta","msg-status","msg-time","tail","status-dblcheck","msg-dblcheck","msg-check"].includes(t))return!0;return/\\b(message-meta|copyable-text-selectable|x1rg5ohu|x16dsc37)\\b/.test(o)},
stripTrailingMessageMeta(i){if(!i)return"";return i.replace(/\\u200b/g,"").replace(/\\n{3,}/g,"\\n\\n").replace(/[\\s\\u00a0]+/g," ").replace(/(?:\\s|[\\u200b\\u2060])*(?:\\d{1,2}:\\d{2})(?:\\s*[✓✔↻⟳]+)?$/u,"").trim()},
extractMessageText(i){if(!i)return"";const e=YUNYI_WHATSAPP_HOST.extractMessageRow(i)||i,t=Array.from(e.querySelectorAll?.("[data-testid='msg-text'] span.selectable-text.copyable-text,[data-testid='msg-text'] p.copyable-text,[data-testid='msg-text'] [data-lexical-text='true'],span.selectable-text.copyable-text,p.copyable-text")||[]).filter(n=>!YUNYI_WHATSAPP_HOST.isMetaMessageElement(n));if(t.length){const n=t.map(r=>String(r.textContent||"").trim()).filter(Boolean).join("\\n");if(n)return YUNYI_WHATSAPP_HOST.stripTrailingMessageMeta(n)}const o=(n,r)=>{if(!n)return;if(n.nodeType===Node.TEXT_NODE){const l=String(n.textContent||"");l&&r.push(l);return}if(n.nodeType!==Node.ELEMENT_NODE)return;const u=n;if(YUNYI_WHATSAPP_HOST.isMetaMessageElement(u))return;if(u.tagName==="BR"){r.push("\\n");return}if(u.tagName==="IMG"){const l=String(u.getAttribute("alt")||"");l&&r.push(l);return}for(const l of Array.from(u.childNodes||[]))o(l,r)},a=i.matches?.("[data-testid='msg-text'],._akbu,span.selectable-text.copyable-text,p.copyable-text")?i:i.querySelector?.("[data-testid='msg-text'],._akbu,span.selectable-text.copyable-text,p.copyable-text")||e,s=[];o(a,s);return YUNYI_WHATSAPP_HOST.stripTrailingMessageMeta(s.join(""))}`;
}
